services:
    sigredis:
        image: redis:7.0.10-alpine
        container_name: sigredis
        restart: always
        # ports:
        #  - 7379:7379
        expose:
            - '${REDIS_PORT:-6379}'
        tty: true
    sigapp:
        build: .
        container_name: sigapp
        init: true
        restart: always
        tty: true
        env_file: ${PWD}/.env
        ports:
         - 3030:3030
        expose:
            - ${APP_PORT:-3030}
            - ${API_PORT:-3031}
            - ${REDIS_HOST:-localhost}
            - ${REDIS_PORT:-6379}
        depends_on:
            - sigredis